language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

dist: trusty # 系统版本
sudo: false  # 是否使用 sudo 模式

# 执行前需要运行的命令
install: travis_retry composer install --no-interaction --prefer-source

# 主要构建命令
script: vendor/bin/phpunit --verbose
